version: "3.8"
services:
  api:
    container_name: aiohttp-balance-api
    build: .
    command: bash -c "../python -m app"
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app

